#If true, when a new frontier is created, the first vertex will automatically be added where the player is.
addVertexToNewFrontier = true
#With true, it always shows unfinished frontiers. With false, they will only be seen with the book in hand.
alwaysShowUnfinishedFrontiers = true
#Force all frontier names to be shown on the map or hidden. In Manual you can decide for each frontier.
#Allowed Values: Manual, Show, Hide
nameVisibility = "Manual"
#Transparency of the frontier polygons. 0.0 is fully transparent and 1.0 is no transparency.
#Range: 0.0 ~ 1.0
polygonsOpacity = 0.4
#Distance at which vertices are attached to nearby vertices.
#Range: 0 ~ 16
snapDistance = 8

[hud]
	#Size of the HUD banner.
	#Range: > -2147483648
	xPosition = 0
	#HUD element on slot 3.
	#Allowed Values: None, Name, Owner, Banner
	slot3 = "Banner"
	#HUD element on slot 2.
	#Allowed Values: None, Name, Owner, Banner
	slot2 = "Owner"
	#HUD element on slot 1.
	#Allowed Values: None, Name, Owner, Banner
	slot1 = "Name"
	#Anchor point of the HUD. In the case of choosing the minimap as an anchor, its default position will be used as a reference in the coordinates.
	#Allowed Values: ScreenTop, ScreenTopRight, ScreenRight, ScreenBottomRight, ScreenBottom, ScreenBottomLeft, ScreenLeft, ScreenTopLeft, Minimap, MinimapHorizontal, MinimapVertical
	anchor = "MinimapHorizontal"
	#Size of the HUD banner.
	#Range: > -2147483648
	yPosition = 0
	#Size of the HUD banner.
	#Range: 1 ~ 8
	bannerSize = 3
	#Show the HUD on screen.
	enabled = true
	#Automatically switch to nearest anchor when HUD position is edited (on settings screen).
	autoAdjustAnchor = true
	#Automatically snap to closest border when HUD position is edited (on settings screen).
	snapToBorder = true

