
[Information]
	"Enable season HUD" = false
	"Show wet/dry tooltip" = false
	#This config option requires Enable season HUD to be true. If it is false it will not work.
	"Require calendar items in inventory to display the HUD" = false
	"Enable seasonal music" = false
	"Display season in debug menu" = true
	"Enable crops season tooltip" = true

[Weather]
	"Enable blizzard texture" = true
	#Range: 0 ~ 100
	"Fog density multiplier (Blizzard)" = 25
	#Range: 0 ~ 100
	"Fog density multiplier (Fog)" = 10
	#Allowed Values: OFF, STANDARD, SANDY
	"Dry biomes fog style" = "SANDY"
	"Enable blizzard sound effect" = true
	#Set this to 0 to disable all types of fogs
	#Range: 0 ~ 100
	"Fog/Blizzard density" = 20
	#Range: 0 ~ 100
	"Fog density multiplier (Snow)" = 5
	#Range: 0 ~ 100
	"Fog density multiplier (Dry Fog)" = 15

